service: alb-s3-sqs-es

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: true
    invalidateCaches: true

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-southeast-2
  lambdaHashingVersion: 20201221

functions:
  alb-s3:
    handler: alb_s3/run.lambda_handler
