on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:

name: Create Lambda Releases

jobs:
  build:
    name: Create Lambda Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test ALB
        working-directory: alb-s3-sqs-es/src/
        run: |
          pip install -r requirements.txt
          pytest

      - name: Build alb project
        working-directory: alb-s3-sqs-es/
        run: |
          npm ci
          npx sls package

      - name: Build cw firehose project
        working-directory: cloudwatch-firehose-es/
        run: |
          npm ci
          npx sls package

      - name: Create Tag Release
        id: create_tag_release
        uses: actions/create-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref  }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload alb asset
        id: upload_alb_release_asset
        uses: actions/upload-release-asset@v1
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_tag_release.outputs.upload_url }}
          asset_path: alb-s3-sqs-es/.serverless/alb-s3-sqs-es.zip
          asset_name: alb-s3.zip
          asset_content_type: application/zip

      - name: Upload cw firehose asset
        id: upload_cw_firehose_release_asset
        uses: actions/upload-release-asset@v1
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_tag_release.outputs.upload_url }}
          asset_path: cloudwatch-firehose-es/.serverless/cloudwatch-firehose.zip
          asset_name: cloudwatch-firehose.zip
          asset_content_type: application/zip
